### ISSUE TITLE
Not compatible with okhttp-idling-resource

### ISSUE THREAD

**Issue by rocboronat** [JakeWharton/retrofit1-okhttp3-client#4]
When using `retrofit1-okhttp3-client` with `okhttp-idling-resource`, the IdlingResource lanches a `NoSuchMethodError`. It seems that the OkHttpClient doesn't have the `setIdleCallback()` method.

```java
java.lang.NoSuchMethodError: okhttp3.Dispatcher.setIdleCallback
at com.jakewharton.espresso.OkHttp3IdlingResource.<init>(OkHttp3IdlingResource.java:45)
at com.jakewharton.espresso.OkHttp3IdlingResource.create(OkHttp3IdlingResource.java:35)
at com.anuntis.fotocasa.testutils.OkHttpIdlingResourceRule$1.evaluate(OkHttpIdlingResourceRule.java:19)
at com.schibsted.spain.barista.cleardata.ClearFilesRule$1.evaluate(ClearFilesRule.java:20)
at com.schibsted.spain.barista.cleardata.ClearDatabaseRule$1.evaluate(ClearDatabaseRule.java:20)
at com.schibsted.spain.barista.cleardata.ClearPreferencesRule$1.evaluate(ClearPreferencesRule.java:26)
...
```

By the way, as I don't know if this is a responsability of `retrofit1-okhttp3-client` or `okhttp-idling-resource`, I'm opening the issue on both projects. Feel free of closing the issue on the project where it doesn't apply.

Thanks for the good work!

**Comment by JakeWharton** [comment]
It's not going to be a problem in either library. I commented on the other issue though.
